<?php
/**
 * Author: VietKhanh
 * File: func.php
 * Description: Chú thích các biến cho ae dễ chỉnh
 */
// ============ SETTINGS CHUNG ============ //
$marginRightOption = 70; // Trái/phải (giảm = trái, tăng = phải)
$marginTopOption = 50; // Lên/xuống (giảm = lên, tăng = xuống)
$sizeSignal = [55, 35]; // Kích thước sóng
$sizeWifi = [50, 35]; // Kích thước Wi-Fi
$sizePin = [75, 35]; // Kích thước pin
$fontSizeTinHieu = 31; // Cỡ chữ tín hiệu (LTE|4G|5G)
$displayTinHieu = 'dark'; // Màu tín hiệu ('light' hoặc 'dark')
$sizeDynamics = [505, 170]; // Kích thước Dynamics
// ========== SETTINGS RIÊNG  ==============
$yOffsetSignal = 0; // Lên/xuống sóng
$yOffsetWifi = 0; // Lên/xuống Wi-Fi
$yOffsetMangText = 22; // Lên/xuống chữ mạng
$yOffsetMang = 17; // Lên/xuống icon mạng
$yOffsetPin = 0; // Lên/xuống pin
// ===== KHOẢNG CÁCH TÍN HIỆU/SÓNG/PIN =====
$spacingCombo = 15;
// ====================================== //
$configDefault = 
[
    // ============ BILL CK ============ //
    //  'mbbank' => [
    //      'marginRightOption' => 70,
    //      'marginTopOption' => 50,
    //      'sizeSignal' => [55, 35],
    //      'sizeWifi' => [50, 35],
    //      'sizePin' => [75, 35],
    //      'fontSizeTinHieu' => 31,
    //      'displayTinHieu' => 'dark',
    //      'sizeDynamics' => [505, 170],
    //      'yOffsetSignal' => 0,
    //      'yOffsetWifi' => 0,
    //      'yOffsetMangText' => 17,
    //      'yOffsetMang' => 17,
    //      'yOffsetPin' => 0,
    //      'spacingCombo' => 15,
    //  ],
      'mbbank' => [
        'marginRightOption' => 70,
        'marginTopOption' => 32,
        'sizeSignal' => [42, 26],
        'sizeWifi' => [37, 27],
        'sizePin' => [59, 26],
        'fontSizeTinHieu' => 24,
        'displayTinHieu' => isset($themeDisplay) ?: $displayTinHieu,
        'sizeDynamics' => [340, 117],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -1,
        'yOffsetMangText' => 14,
        'yOffsetMang' => 17,
        'yOffsetPin' =>0,
        'spacingCombo' => 12,
    ],
    //  'mbbank-don-luu' => [
    //     'marginRightOption' => 50,
    //     'marginTopOption' => 44,
    //     'sizeSignal' => [40, 23],
    //     'sizeWifi' => [35, 24],
    //     'sizePin' => [55, 24],
    //     'fontSizeTinHieu' => 32,
    //     'displayTinHieu' => $themeDisplay,
    //     'sizeDynamics' => [390, 130],
    //     'yOffsetSignal' => 0,
    //     'yOffsetWifi' => -1,
    //     'yOffsetMangText' => 19,
    //     'yOffsetMang' => 17,
    //     'yOffsetPin' => -1,
    //     'spacingCombo' => 13,
    // ],
    'mbbank-tet' => [
        'marginRightOption' => 72,
        'marginTopOption' => 66,
        'sizeSignal' => [61, 41],
        'sizeWifi' => [55, 40],
        'sizePin' => [88, 40],
        'fontSizeTinHieu' => 36,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 22,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'mbbank-priority' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 30,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 17,
        'yOffsetMangText' => 18,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vietcombank' => [
        'marginRightOption' => 64,
        'marginTopOption' => 53,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [49, 34],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 18,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vietcombank-priority' => [
        'marginRightOption' => 54,
        'marginTopOption' => 33,
        'sizeSignal' => [49, 29],
        'sizeWifi' => [37, 28],
        'sizePin' => [59, 29],
        'fontSizeTinHieu' => 26,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [345, 130],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 17,
        'yOffsetPin' => 2,
        'spacingCombo' => 14,
    ],
    'vcb-galaxy' => [
        'marginRightOption' => 62,
        'marginTopOption' => 33,
        'sizeSignal' => [49, 29],
        'sizeWifi' => [38, 28],
        'sizePin' => [59, 29],
        'fontSizeTinHieu' => 26,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [345, 130],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 17,
        'yOffsetPin' => 1,
        'spacingCombo' => 14,
    ],
    'techcombank' => [
        'marginRightOption' => 50,
        'marginTopOption' => 40,
        'sizeSignal' => [40, 25],
        'sizeWifi' => [35, 27],
        'sizePin' => [57, 28],
        'fontSizeTinHieu' => 23,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [350, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -2,
        'yOffsetMang' => 17,
        'yOffsetMangText' => 12,
        'yOffsetPin' => -1,
        'spacingCombo' => 13,
    ],
    'vietinbank' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 30,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 17,
        'yOffsetMangText' => 18,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vietinbankred' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [60, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [70, 35],
        'fontSizeTinHieu' => 30,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 17,
        'yOffsetMangText' => 18,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'acb' => [
        'marginRightOption' => 64,
        'marginTopOption' => 55,
        'sizeSignal' => [60, 40],
        'sizeWifi' => [55, 38],
        'sizePin' => [80, 40],
        'fontSizeTinHieu' => 34,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 21,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'momo' => [
        'marginRightOption' => 64,
        'marginTopOption' => 54,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'zalopay' => [
        'marginRightOption' => 64,
        'marginTopOption' => 60,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [77, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'agribank' => [
        'marginRightOption' => 70,
        'marginTopOption' => 50,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'msb' => [
        'marginRightOption' => 55,
        'marginTopOption' => 56,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'tpbank' => [
        'marginRightOption' => 74,
        'marginTopOption' => 62,
        'sizeSignal' => [60, 40],
        'sizeWifi' => [55, 40],
        'sizePin' => [80, 37],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 2,
        'spacingCombo' => 14,
    ],
    'tpbank-new' => [
        'marginRightOption' => 84,
        'marginTopOption' => 52,
        'sizeSignal' => [60, 40],
        'sizeWifi' => [55, 40],
        'sizePin' => [80, 37],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 4,
        'spacingCombo' => 14,
    ],
    'vpbank' => [
        'marginRightOption' => 78,
        'marginTopOption' => 58,
        'sizeSignal' => [58, 38],
        'sizeWifi' => [53, 38],
        'sizePin' => [80, 38],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 19,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'sell-binance' => [
        'marginRightOption' => 70,
        'marginTopOption' => 70,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [550, 190],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    'buy-binance' => [
        'marginRightOption' => 65,
        'marginTopOption' => 42,
        'sizeSignal' => [50, 30],
        'sizeWifi' => [39, 30],
        'sizePin' => [65, 30],
        'fontSizeTinHieu' => 27,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [330, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 17,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    'bvbank' => [
        'marginRightOption' => 118,
        'marginTopOption' => 49,
        'sizeSignal' => [63, 48],
        'sizeWifi'   => [58, 49],
        'sizePin'    => [84, 48],
        'fontSizeTinHieu' => 39,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [237, 85],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -1,
        'yOffsetMang' => 17,
        'yOffsetMangText' => 23,
        'yOffsetPin' => 0,
        'spacingCombo' => 18,
    ],
    'seabank' => [
        'marginRightOption' => 120,
        'marginTopOption' => 70,
        'sizeSignal' => [61, 36],
        'sizeWifi'   => [56, 37],
        'sizePin'    => [72, 36],
        'fontSizeTinHieu' => 35,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [500, 200],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -1,
        'yOffsetMang' => 17,
        'yOffsetMangText' => 18,
        'yOffsetPin' => 0,
        'spacingCombo' => 17,
    ],
    'bacabank' => [
        'marginRightOption' => 64,
        'marginTopOption' => 53,
        'sizeSignal' => [60, 40],
        'sizeWifi'   => [54, 39],
        'sizePin'    => [83, 40], 
        'fontSizeTinHieu' => 32,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 21,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'viettel-money' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 30,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 17,
        'yOffsetMangText' => 18,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'hdbank' => [
        'marginRightOption' => 140,
        'marginTopOption' => 45,
        'sizeSignal' => [60, 40],
        'sizeWifi'   => [54, 39],
        'sizePin'    => [83, 40], 
        'fontSizeTinHieu' => 32,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 21,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'seabank-premium' => [
        'marginRightOption' => 120,
        'marginTopOption' => 55,
        'sizeSignal' => [65, 45],
        'sizeWifi'   => [59, 44],
        'sizePin'    => [88, 45],
        'fontSizeTinHieu' => 35,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 21,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vietbank' => [
        'marginRightOption' => 80,
        'marginTopOption' => 55,
        'sizeSignal' => [65, 45],
        'sizeWifi'   => [59, 44],
        'sizePin'    => [88, 45],
        'fontSizeTinHieu' => 37,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 23,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vibbank' => [
        'marginRightOption' => 80,
        'marginTopOption' => 55,
        'sizeSignal' => [65, 45],
        'sizeWifi'   => [59, 44],
        'sizePin'    => [88, 45],
        'fontSizeTinHieu' => 37,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 23,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'acb-privilege' => [
        'marginRightOption' => 80,
        'marginTopOption' => 55,
        'sizeSignal' => [50, 30],
        'sizeWifi'   => [40, 30],
        'sizePin'    => [73, 30],
        'fontSizeTinHieu' => 28,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [420, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 16,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'bidv' => [
        'marginRightOption' => 50,
        'marginTopOption' => 49,
        'sizeSignal' => [45, 28],
        'sizeWifi' => [43, 30],
        'sizePin' => [63, 29],
        'fontSizeTinHieu' => 27,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [400, 135],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -3,
        'yOffsetMangText' => 14,
        'yOffsetMang' => 17,
        'yOffsetPin' => -2,
        'spacingCombo' => 14,
    ],
    'pgbank' => [
        'marginRightOption' => 45,
        'marginTopOption' => 30,
        'sizeSignal' => [32, 21],
        'sizeWifi'   => [32, 21],
        'sizePin'    => [42, 21],
        'fontSizeTinHieu' => 17,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [280, 100],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 12,
        'yOffsetPin' => 0,
        'spacingCombo' => 10,
    ],
    'liobank' => [
        'marginRightOption' => 40,
        'marginTopOption' => 30,
        'sizeSignal' => [32, 21],
        'sizeWifi'   => [32, 21],
        'sizePin'    => [42, 21],
        'fontSizeTinHieu' => 17,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [250, 105],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 12,
        'yOffsetPin' => 0,
        'spacingCombo' => 10,
    ],
    'shinhanbank' => [
        'marginRightOption' => 75,
        'marginTopOption' => 40,
        'sizeSignal' => [50, 30],
        'sizeWifi'   => [40, 30],
        'sizePin'    => [68, 30],
        'fontSizeTinHieu' => 25,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [390, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 15,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'sacombank' => [
        'marginRightOption' => 50,
        'marginTopOption' => 40,
        'sizeSignal' => [50, 30],
        'sizeWifi'   => [40, 30],
        'sizePin'    => [68, 30],
        'fontSizeTinHieu' => 25,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [390, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 15,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'cake' => [
    'marginRightOption' => 43, 
    'marginTopOption' => 42, 
    'sizeSignal' => [44, 25],
    'sizeWifi' => [39, 27],
    'sizePin' => [60, 27],
    'fontSizeTinHieu' => 25,
    'displayTinHieu' => isset($themeDisplay) ?: $displayTinHieu,
    'sizeDynamics' => [330, 115],
    'yOffsetSignal' => 0,
    'yOffsetWifi' => 0,
    'yOffsetMangText' => 14,
    'yOffsetMang' => 17,
    'yOffsetPin' => 0,
    'spacingCombo' => 14,
    ],
    'worri' => [
        'marginRightOption' => 50,
        'marginTopOption' => 40,
        'sizeSignal' => [40, 26],
        'sizeWifi'   => [35, 25],
        'sizePin'    => [58, 27],
        'fontSizeTinHieu' => 23,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [330, 140],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 14,
        'yOffsetPin' => 0,
        'spacingCombo' => 12,
    ],
    'namabank' => [
        'marginRightOption' => 70,
        'marginTopOption' => 60,
        'sizeSignal' => [72, 41],   //72, 41
        'sizeWifi'   => [54, 38],  //67, 40
        'sizePin'    => [80, 42], //80, 42
        'fontSizeTinHieu' => 35,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [430, 180],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 22,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'pvbank' => [
        'marginRightOption' => 72,
        'marginTopOption' => 66,
        'sizeSignal' => [61, 41],
        'sizeWifi' => [55, 40],
        'sizePin' => [88, 40],
        'fontSizeTinHieu' => 36,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 22,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'ocb' => [
        'marginRightOption' => 72,
        'marginTopOption' => 55,
        'sizeSignal' => [61, 41],
        'sizeWifi' => [55, 40],
        'sizePin' => [88, 40],
        'fontSizeTinHieu' => 36,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 22,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'chinhsachxahoi' => [
        'marginRightOption' => 72,
        'marginTopOption' => 55,
        'sizeSignal' => [61, 41],
        'sizeWifi' => [55, 40],
        'sizePin' => [88, 40],
        'fontSizeTinHieu' => 36,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [450, 175],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 22,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'eximbank' => [
        'marginRightOption' => 65,
        'marginTopOption' => 28,
        'sizeSignal' => [45, 28],
        'sizeWifi' => [38, 28],
        'sizePin' => [55, 28],
        'fontSizeTinHieu' => 23,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [300, 125],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 16,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'saigonbank' => [
        'marginRightOption' => 65,
        'marginTopOption' => 55,
        'sizeSignal' => [75, 45],
        'sizeWifi' => [60, 45],
        'sizePin' => [85, 45],
        'fontSizeTinHieu' => 38,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [450, 220],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 25,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'abbank' => [
        'marginRightOption' => 80,
        'marginTopOption' => 60,
        'sizeSignal' => [75, 45],
        'sizeWifi' => [60, 45],
        'sizePin' => [85, 45],
        'fontSizeTinHieu' => 38,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [380, 150],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 25,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'okx' => [
        'marginRightOption' => 65,
        'marginTopOption' => 44,
        'sizeSignal' => [50, 30],
        'sizeWifi' => [43, 30],
        'sizePin' => [59, 30],
        'fontSizeTinHieu' => 25,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [320, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 16,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'ncb' => [
        'marginRightOption' => 80,
        'marginTopOption' => 66,
        'sizeSignal' => [72, 45],
        'sizeWifi' => [62, 45],
        'sizePin' => [90, 46],
        'fontSizeTinHieu' => 36,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [370, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 24,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'lpbank' => [
        'marginRightOption' => 80,
        'marginTopOption' => 43,
        'sizeSignal' => [72, 45],
        'sizeWifi' => [62, 45],
        'sizePin' => [90, 46],
        'fontSizeTinHieu' => 36,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [400, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 24,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'kienlongbank' => [
        'marginRightOption' => 80,
        'marginTopOption' => 63,
        'sizeSignal' => [72, 45],
        'sizeWifi' => [62, 45],
        'sizePin' => [90, 46],
        'fontSizeTinHieu' => 37,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [400, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 24,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'bidv-premier' => [
        'marginRightOption' => 60,
        'marginTopOption' => 40,
        'sizeSignal' => [52, 30],
        'sizeWifi' => [42, 29],
        'sizePin' => [65, 30],
        'fontSizeTinHieu' => 26,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [300, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 16,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'shb' => [
        'marginRightOption' => 90,
        'marginTopOption' => 50,
        'sizeSignal' => [60, 42],
        'sizeWifi' => [56, 41],
        'sizePin' => [91, 42],
        'fontSizeTinHieu' => 32,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [400, 180],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 15,
        'yOffsetMangText' => 23,
        'yOffsetPin' => 0,
        'spacingCombo' => 16,
    ],
    'vietcombank-new' => [
        'marginRightOption' => 64,
        'marginTopOption' => 53,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [49, 34],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMang' => 16,
        'yOffsetMangText' => 18,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'acb-new' => [
        'marginRightOption' => 64,
        'marginTopOption' => 55,
        'sizeSignal' => [60, 40],
        'sizeWifi' => [55, 38],
        'sizePin' => [80, 40],
        'fontSizeTinHieu' => 34,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 21,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    // ============ BILL SO DU ============ //
    'sodu-vietinbank' => [
        'marginRightOption' => 70,
        'marginTopOption' => 47,
        'sizeSignal' => [59, 39],
        'sizeWifi' => [52, 38],
        'sizePin' => [79, 35],
        'fontSizeTinHieu' => 27,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -2,
        'yOffsetMangText' => 21,
        'yOffsetMang' => 17,
        'yOffsetPin' => 2,
        'spacingCombo' => 15,
    ],
    'sodu-momo' => [
        'marginRightOption' => 72,
        'marginTopOption' => 50,
        'sizeSignal' => [62, 42],
        'sizeWifi' => [55, 40],
        'sizePin' => [84, 39],
        'fontSizeTinHieu' => 34,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -2,
        'yOffsetMangText' => 23,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    'sodu-mbbank' => [
        'marginRightOption' => 60,
        'marginTopOption' => 53,
        'sizeSignal' => [57, 37],
        'sizeWifi' => [49, 35],
        'sizePin' => [77, 34],
        'fontSizeTinHieu' => 32,
        'displayTinHieu' => isset($themeNw) ?: 'con cac lỏ xỏ lòn heo',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 19,
        'yOffsetMang' => 17,
        'yOffsetPin' => 2,
        'spacingCombo' => 15,
    ],
    'sodu-zalopay' => [
        'marginRightOption' => 75,
        'marginTopOption' => 50,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [78, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -2,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'sodu-acb' => [
        'marginRightOption' => 68,
        'marginTopOption' => 50,
        'sizeSignal' => [58, 38],
        'sizeWifi' => [53, 38],
        'sizePin' => [78, 35],
        'fontSizeTinHieu' => 32,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -2,
        'yOffsetMangText' => 21,
        'yOffsetMang' => 17,
        'yOffsetPin' => 2,
        'spacingCombo' => 15,
    ],
   'sodu-techcombank' => [
        'marginRightOption' => 60,
        'marginTopOption' => 53,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [78, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -2,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'sodu-mbbank-priority' => [
        'marginRightOption' => 60,
        'marginTopOption' => 53,
        'sizeSignal' => [57, 37],
        'sizeWifi' => [49, 35],
        'sizePin' => [77, 34],
        'fontSizeTinHieu' => 32,
        'displayTinHieu' => isset($themeNw) ?: 'con cac lỏ xỏ lòn heo',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 19,
        'yOffsetMang' => 17,
        'yOffsetPin' => 2,
        'spacingCombo' => 15,
    ],
    'sodu-cake' => [
        'marginRightOption' => 20,  
        'marginTopOption' => 32,    
        'sizeSignal' => [48, 28],  
        'sizeWifi'   => [43, 28],  
        'sizePin' => [53, 28],
        'fontSizeTinHieu' => 25,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [320, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -0,
        'yOffsetMangText' => 16,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    'sodu-agribank' => [
        'marginRightOption' => 65,  
        'marginTopOption' => 41,    
        'sizeSignal' => [48, 33],  
        'sizeWifi'   => [42, 31],  
        'sizePin' => [63, 33],
        'fontSizeTinHieu' => 27,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [320, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    'sodu-tpbank' => [
        'marginRightOption' => 85,  
        'marginTopOption' => 52,    
        'sizeSignal' => [48, 33],  
        'sizeWifi'   => [42, 31],  
        'sizePin' => [63, 33],
        'fontSizeTinHieu' => 27,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [320, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    'sodu-vpbank' => [
        'marginRightOption' => 85,  
        'marginTopOption' => 52,    
        'sizeSignal' => [48, 33],  
        'sizeWifi'   => [42, 31],  
        'sizePin' => [63, 33],
        'fontSizeTinHieu' => 27,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [320, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    'sodu-vcb' => [
        'marginRightOption' => 85,  
        'marginTopOption' => 52,    
        'sizeSignal' => [48, 33],  
        'sizeWifi'   => [42, 31],  
        'sizePin' => [63, 33],
        'fontSizeTinHieu' => 27,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [320, 120],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => -0,
        'yOffsetMangText' => 18,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 15,
    ],
    // ============ BILL BDSD ============ //
    'bdsd-mbbank' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [51, 31],
        'sizeWifi' => [46, 31],
        'sizePin' => [71, 33],
        'fontSizeTinHieu' => 29,
        'displayTinHieu' => 'dark',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 16,
        'yOffsetMang' => 17,
        'yOffsetPin' => -1,
        'spacingCombo' => 14,
    ],
    'bdsd-techcombank' => [
        'marginRightOption' => 45,
        'marginTopOption' => 27,
        'sizeSignal' => [33, 17],
        'sizeWifi' => [25, 18],
        'sizePin' => [41, 18],
        'fontSizeTinHieu' => 16,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [260, 90],
        'yOffsetSignal' => -1,
        'yOffsetWifi' => -3,
        'yOffsetMangText' => 6,
        'yOffsetMang' => 13,
        'yOffsetPin' => -3,
        'spacingCombo' => 8,
    ],
    // ============ BILL KHAC ============ //
    'mbbank-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'acb-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'momo-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'binance-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vcb-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'zalopay-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'zlpay-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'bidv-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'sacombankpay-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vietinbank-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'techcombank-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'vib-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'msb-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'tpbank-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],
    'agribank-man-hinh-khoa' => [
        'marginRightOption' => 64,
        'marginTopOption' => 45,
        'sizeSignal' => [55, 35],
        'sizeWifi' => [50, 35],
        'sizePin' => [75, 35],
        'fontSizeTinHieu' => 31,
        'displayTinHieu' => 'light',
        'sizeDynamics' => [505, 170],
        'yOffsetSignal' => 0,
        'yOffsetWifi' => 0,
        'yOffsetMangText' => 22,
        'yOffsetMang' => 17,
        'yOffsetPin' => 0,
        'spacingCombo' => 14,
    ],

 ];
 $percentPin = $_POST['percent-pin'] ?? 'off';
 if ($percentPin === 'on' && in_array($_POST['pin'], [58])) 
 {
    die(JSON_FORMATTER(["status" => 403, 'msg' => 'Xin lỗi vì sự bất tiện, hiện tại số pin '.$_POST['pin'].'% không khả dụng, bạn vui lòng nhập số phần trăm pin khác hoặc có thể ẩn hiện % pin 😩.']));
}
if (isset($configDefault[$_POST['action']])) {
    $settings = $configDefault[$_POST['action']];
    // Chỉnh sửa kích thước pin % 👇
    if ($percentPin === 'on') {
        switch ($_POST['action']) {
            // ============ BILL CK ============ //
            case 'mbbank-tet':
                $settings['sizePin'] = [90, 41];
                $settings['yOffsetPin'] -= 2;
                break;
            // case 'mbbank':
            //     $settings['sizePin'] = [78, 35];
            //     $settings['yOffsetPin'] -= 2;
            //     break;
            case 'mbbank':
                $settings['yOffsetPin'] -= 0;
                break;
            case 'vietcombank':
                $settings['sizePin'] = [80, 37];
                $settings['yOffsetPin'] -= 3;
                break;
            case 'techcombank':
                $settings['sizePin'] = [49, 27];
                $settings['yOffsetPin'] -= 3;
                break;
            case 'vietinbank':
                $settings['yOffsetPin'] -= 2;
                    break;
            case 'acb':
                $settings['sizePin'] = [82, 38];
                $settings['yOffsetPin'] -= 2;
                 break;
            case 'momo':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'zalopay':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'agribank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'msb':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'tpbank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'vpbank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'worri':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'sell-binance':
                 $settings['sizePin'] = [78, 35];
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'mbbank-priority':
                $settings['sizePin'] = [80, 35];
                 $settings['yOffsetPin'] -= 2;
                 break;
            // ============ BILL SO DU ============ //
            case 'sodu-vietinbank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'sodu-momo':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'sodu-mbbank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'sodu-zalopay':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'sodu-acb':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'sodu-agribank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            // ============ BILL BDSD ============ //
            case 'bdsd-mbbank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            case 'bdsd-vietinbank':
                 $settings['yOffsetPin'] -= 2;
                 break;
            // ============ BILL KHAC ============ //
            case 'mbbank-man-hinh-khoa':
                 $settings['yOffsetPin'] -= 2;
                 break;
            default:
                break;
        }
    }
    extract($settings);
} else {
    die(JSON_FORMATTER(["status" => 403, 'msg' => 'The action '.strtoupper($_POST['action']).' has not been configured or could not be found. Please check again in the file named func.php']));
}
