<?php 
$databaseWs=new THANHDIEUSTART();
  $databaseWs->setDatabaseCharset();
   $databaseWs->setSessionRequestTime();
    $userAgent=$databaseWs->getUserAgent();
     $time=$databaseWs->getCurrentTime();
      $timeft=$databaseWs->getFormatCurrentTime();
       $website_domain=$databaseWs->getWebsiteDomain();
         $current_url=$databaseWs->getCurrentURL();
          $domain=$databaseWs->getDomain();
            $actual_link=$databaseWs->getFullURL();
              $phpversion=$databaseWs->getPHPVersion();
                $serversoftware=$databaseWs->getServerSoftware();
                  $msqlicheck=$databaseWs->getMysqliCheck();
                    $mysqlversion=DatabaseConnection::ThanhDieuDB()->get_server_info();
                      $ip=$databaseWs->getIPClient();
                        $split=new HidedHtml\Obfuscator();
                         $SSC=new SessionExpiredChecker();
                          $planChecker=new CheckPlanStatus();
                            $planInfo=$planChecker->TD($taikhoan);
                              $isLogin=new CheckSessionLogin();
                                $limitbill=new LimitBill();
                                 $freebill=new FreeBill();
                                   $browsers = new BrowserSupport();
                                    $backupRemove=new BackupRemove();
  /* ThanhDieu.Com */                $backupRemove->RemoveBackup(2);
                                     $Bill = new Bill($current_url);
                                    $Bill->fakebill();
                                  $Bill->check();
                               remove_expired_alom();
                            //   ClearIMGProduct();
                            $plans=new Plans();
                          $cut=new TextCutter();
                       $update=new WussunSQL();
                     $into=new WussunSQL();
                   $CheckSession=new CheckSSK($user);
                //  $CheckSession->check();
               $RequestUpdater=new RequestPageCount();
             $totals=new TotalGolbal($taikhoan);
            $transfer=new Transfer();
           (new BlacklistChecker())->blacklist($ip, $TD);
          $browser_info=new BrowserInfo($userAgent);
         $device_info=new DeviceInfo($userAgent);
       $browser_name=$browser_info->name;
      $browser_icon="icon-".strtolower(str_replace(" ", "",$browser_info->icon));
     $device_name=$device_info->name;
    $device_icon="icon-".strtolower(str_replace(" ", "", $device_info->icon));
   include($_SERVER['DOCUMENT_ROOT'].'/vendor/phpmailer/phpmailer/smtp-maller.php');
  $thanhdieudb->query("DELETE FROM ws_otpmailler WHERE is_used=0 AND expires_at <= NOW()");
 PlanExpiredChecker::TD();
$history_goivip=new VIPHistory();